import { normalTime } from './time_format'
import { monthDay } from './get_month_day'
import { level, playLevel } from './level'
import { monthDaySecond } from './get_month_day_second'
import { getTheImage } from './get_the_image'
import { getLength } from './get_string_length'
import { getLengthPonit, getLengthPonitInside } from './get_string_point'
import { number } from './number'
import { age, ageYear } from './age'
import { format, MathFloor, defaultUser } from './format'
import { smallImage } from './small_image'
import { formatUnderfind } from './format_underfind'
import { reward } from './get_reward'
import { koType } from './ko_type'
import { addZero } from './time_add_zero'
import { status } from './status'
export default {normalTime, monthDay, level, playLevel, monthDaySecond, getTheImage, getLength, getLengthPonit, getLengthPonitInside, number, age, format, MathFloor, smallImage, formatUnderfind, reward, koType, addZero, status,defaultUser,ageYear}
